version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
    

    rabbitmq:
        image: rabbitmq:3.8.2-management
        ports:
          - 5672:5672
          - 15672:15672
    
    nginx:
        image: nginx:latest
        ports:
          - 80:80
        volumes:
          - ../webService:/code
          - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
          - php
    php:
       image: php:7-fpm
       volumes:
         - ../webService:/code