// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buffer.proto

package main

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e21993b51421452, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Buffer struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Count                int64    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image                []byte   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Blocks               []*Point `protobuf:"bytes,6,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Buffer) Reset()         { *m = Buffer{} }
func (m *Buffer) String() string { return proto.CompactTextString(m) }
func (*Buffer) ProtoMessage()    {}
func (*Buffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e21993b51421452, []int{1}
}

func (m *Buffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Buffer.Unmarshal(m, b)
}
func (m *Buffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Buffer.Marshal(b, m, deterministic)
}
func (m *Buffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buffer.Merge(m, src)
}
func (m *Buffer) XXX_Size() int {
	return xxx_messageInfo_Buffer.Size(m)
}
func (m *Buffer) XXX_DiscardUnknown() {
	xxx_messageInfo_Buffer.DiscardUnknown(m)
}

var xxx_messageInfo_Buffer proto.InternalMessageInfo

func (m *Buffer) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Buffer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Buffer) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Buffer) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Buffer) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Buffer) GetBlocks() []*Point {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*Point)(nil), "main.Point")
	proto.RegisterType((*Buffer)(nil), "main.Buffer")
}

func init() {
	proto.RegisterFile("buffer.proto", fileDescriptor_1e21993b51421452)
}

var fileDescriptor_1e21993b51421452 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x2c, 0x8f, 0x3d, 0xce, 0x83, 0x30,
	0x0c, 0x86, 0x15, 0x7e, 0x22, 0x7d, 0x86, 0x29, 0xfa, 0x86, 0x8c, 0x08, 0x16, 0x26, 0x86, 0xf6,
	0x06, 0x3d, 0x41, 0x95, 0x1b, 0x00, 0x0d, 0x55, 0xd4, 0x12, 0x57, 0x34, 0x48, 0x70, 0x90, 0xde,
	0xb7, 0xd8, 0xe9, 0xf6, 0x3e, 0x4f, 0x62, 0xeb, 0x35, 0x94, 0xc3, 0x3a, 0x4d, 0x76, 0xe9, 0x5e,
	0x0b, 0x06, 0x54, 0xd9, 0xdc, 0x3b, 0x5f, 0x37, 0x90, 0x5f, 0xd1, 0xf9, 0xa0, 0x4a, 0x10, 0x9b,
	0x16, 0x95, 0x68, 0x53, 0x23, 0x36, 0xa2, 0x5d, 0x27, 0x91, 0xf6, 0xfa, 0x23, 0x40, 0x5e, 0x78,
	0x56, 0x29, 0xc8, 0x82, 0x9b, 0x2d, 0xff, 0xfc, 0x33, 0x9c, 0xc9, 0xf9, 0xfe, 0x70, 0x49, 0x74,
	0x94, 0xc9, 0x8d, 0x78, 0xb3, 0x3a, 0x8d, 0x8e, 0xb2, 0xfa, 0x87, 0x7c, 0xc4, 0xd5, 0x07, 0x9d,
	0xf1, 0xe2, 0x08, 0x64, 0xdd, 0xdc, 0xdf, 0xad, 0xce, 0x0f, 0x5b, 0x9a, 0x08, 0xaa, 0x01, 0x39,
	0x3c, 0x71, 0x7c, 0xbc, 0xb5, 0xac, 0xd2, 0xb6, 0x38, 0x15, 0x1d, 0xd5, 0xed, 0xb8, 0xab, 0xf9,
	0x3d, 0x0d, 0x92, 0x2f, 0x39, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x35, 0x79, 0x00, 0x24, 0xd9,
	0x00, 0x00, 0x00,
}
