kind: PersistentVolume
apiVersion: v1
metadata:
  name: web-test-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/www"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-test-vol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1 
kind: Deployment
metadata:
    name: webtest

spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtest
  template:
    metadata:
      labels:
        app: webtest

  
    spec:
      # Add the ConfigMap as a volume to the Pod
      volumes:
      - name: web-test-vol
        persistentVolumeClaim:
          claimName: web-test-vol
      containers:
      - name: nginx
        image: richarvey/nginx-php-fpm:latest
      # Mount the volume that contains the configuration data 
      # into your container filesystem
        volumeMounts:
        - name: web-test-vol
          mountPath: /var/www/html
